---
- name: Update Apt Cache
  become: yes
  become_user: root
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install git
  become: yes
  become_user: root
  apt:
    pkg: git
    state: present
